# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cedf14ce4e8472fe6df75b86c9a285adac5ddfb1bd5ea7351cb82e0c798c437b790080ca2b1ae7b48d23663661bf364950f3d0f864a6b2079d5efb5396727c1

test:
  secret_key_base: 47726bc04699497cf534cfcb27d1c7da931a6f1f507d27e7c15578ae1639476412e3f339c6186c94ffc20b7d31598f321451678164cfbf45a7bd3cdcff35f976

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
